Prefix: "&8[&f&lJAIL&8]"

Announces:
  onJail: "&7Spilleren &c<player> &7blev sat i jail af &c<guard> &7med grunden: &c<reason> <rank>"

Messages:
  configReloadSuccess: "&7Configen &b<configName> &7blev reloaded"
  configReloadError: "&7Der gik noget galt ved reload af config &b<configName>"

BlockedCommands:
  - /spawn
  - /kaution

JailTimers:
  SlagFange:
    display name: "Slag på fange"
    material: iron sword
    slot: 20
    c: 240
    b: 360
    a: 480